### Numpy 

In [1]:
import typing
import numpy as np

In [ ]:
a_list = [-2, 1, 2]
a_arr = np.array(a_list) 

print(type(a_arr))

In [ ]:
print('Shape of theta_arr:', a_arr.shape)

In [ ]:
# Indexing and slicing is the same for Python lists and numpy arrays
print('Second element of theta_list = ', a_list[1])
print('Second element of theta_arr = ', a_arr[1])

In [ ]:
# Slicing
a_arr[1:]

### Numpy "vectorized" operations

Vectorized operations allow you to perform computations on entire arrays without the need for explicit loops.

In [ ]:
a = np.random.random((10000))
b = np.random.random((10000))

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
a[0:5]

In [ ]:
%%time 

dp = 0 
for i in range(a.shape[0]): 
    dp += a[i]*b[i]
print(dp)

Alternatively, with vectorized operations 

In [ ]:
%%time

np.dot(a, b)

### Matrices 

In [2]:
x2D_array = np.array([[1,2,3],
                      [4, 5, 6]])

print('Shape of x2D_array =', x2D_array.shape)
print('\t num. rows =', x2D_array.shape[0])
print('\t num. columns =', x2D_array.shape[1])

Shape of x2D_array = (2, 3)
	 num. rows = 2
	 num. columns = 3


In [3]:
# You can also modify elements just like in a Python list
print(f"Before:\n {x2D_array}\n")
x2D_array[1][1] = 100
print(f"After:\n {x2D_array}\n")

Before:
 [[1 2 3]
 [4 5 6]]

After:
 [[  1   2   3]
 [  4 100   6]]



In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [6]:
A

array([[1, 2],
       [3, 4]])

In [7]:
B

array([[5, 6],
       [7, 8]])

In [8]:
# Element-wise operation 
A-B

array([[-4, -4],
       [-4, -4]])

In [9]:
# Matrix multiplication 
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

A gentle reminder that matrix multiplication is not transitive! 

In [10]:
np.matmul(B, A)

array([[23, 34],
       [31, 46]])

### Array broadcasting 

"Array broadcasting" is the ability of NumPy to automatically perform element-wise operations on arrays of different shapes by "stretching" the smaller array to match the dimensions of the larger one without physically copying the data.

In [11]:
x2D_array

array([[  1,   2,   3],
       [  4, 100,   6]])

In [12]:
3*x2D_array

array([[  3,   6,   9],
       [ 12, 300,  18]])

In [13]:
# Note, this is NOT how Python list syntax works 
3*[1, 2, 3]

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [14]:
features = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
bias = np.array([0.1, 0.1, 0.1])

In [15]:
features

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [16]:
bias

array([0.1, 0.1, 0.1])

In [17]:
adjusted_vectors = features + bias
print(adjusted_vectors)

[[0.2 0.3 0.4]
 [0.5 0.6 0.7]]
